# version: '3.4'

# services:
#   backend:
#     image: backend
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     environment:
#       NODE_ENV: production
#     ports:
#       - 3000:3000

version: '3'
services:
  db:
    image: mariadb:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tfg_bd
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - .env:/usr/src/app/.env
      - /usr/src/app/node_modules/
    depends_on:
      - db
    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: tfg_bd

volumes:
  db_data:

